menu:
    ByteWidth: 2
    FixedWidth: 8
    Encoding:
        A: 
            code: 0x0000
        B: 
            code: 0x0001
        C: 
            code: 0x0002
        D: 
            code: 0x0003
        E: 
            code: 0x0004
        F: 
            code: 0x0005
        G: 
            code: 0x0006
        H: 
            code: 0x0007
        I: 
            code: 0x0008
        J: 
            code: 0x0009
        K: 
            code: 0x000a
        L: 
            code: 0x000b
        M: 
            code: 0x000c
        N: 
            code: 0x000d
        O: 
            code: 0x000e
        P: 
            code: 0x000f
        Q: 
            code: 0x0010
        R: 
            code: 0x0011
        S: 
            code: 0x0012
        T: 
            code: 0x0013
        U: 
            code: 0x0014
        V: 
            code: 0x0015
        W: 
            code: 0x0016
        X: 
            code: 0x0017
        Y: 
            code: 0x0018
        Z: 
            code: 0x0019
        a: 
            code: 0x001a
        b: 
            code: 0x001b
        c: 
            code: 0x001c
        d: 
            code: 0x001d
        e: 
            code: 0x001e
        f: 
            code: 0x001f
        g: 
            code: 0x0020
        h: 
            code: 0x0021
        i: 
            code: 0x0022
        j: 
            code: 0x0023
        k: 
            code: 0x0024
        l: 
            code: 0x0025
        m: 
            code: 0x0026
        n: 
            code: 0x0027
        o: 
            code: 0x0028
        p: 
            code: 0x0029
        q: 
            code: 0x002a
        r: 
            code: 0x002b
        s: 
            code: 0x002c
        t: 
            code: 0x002d
        u: 
            code: 0x0050
        v: 
            code: 0x0051
        w: 
            code: 0x0052
        x: 
            code: 0x0053
        y: 
            code: 0x0054
        z: 
            code: 0x0055
        "'": 
            code: 0x0056
        ",": 
            code: 0x0057
        "[openparen2]": 
            code: 0x0058
        "[closeparen2]": 
            code: 0x0059
        .: 
            code: 0x005a
        "[space2]": 
            code: 0x005b
        "[semicolon]": 
            code: 0x005d
        0: 
            code: 0x009f
        1: 
            code: 0x00a0
        2: 
            code: 0x00a1
        3: 
            code: 0x00a2
        4: 
            code: 0x00a3
        5: 
            code: 0x00a4
        6: 
            code: 0x00a5
        7: 
            code: 0x00a6
        8: 
            code: 0x00a7
        9: 
            code: 0x00a8
        "[H2]": 
            code: 0x00a9
        "[P2]": 
            code: 0x00aa
        "[L2]": 
            code: 0x00ab
        "[V2]": 
            code: 0x00ac
        "[EX1]": 
            code: 0x00ad
        "[EX2]": 
            code: 0x00ae
        "[M2]": 
            code: 0x00af
        /: 
            code: 0x00b0
        "[D2]": 
            code: 0x00b1
        "[R2]": 
            code: 0x00b2
        "[Y2]": 
            code: 0x00b4
        "[N2]": 
            code: 0x00b5
        "[E2]": 
            code: 0x00b6
        "[S2]": 
            code: 0x00b7
        "[A2]": 
            code: 0x00b8
        "[W2]": 
            code: 0x00b9
        "%": 
            code: 0x00ba
        "[X2]": 
            code: 0x00bb
        _: 
            code: 0x00be
        (: 
            code: 0x00c0
        ): 
            code: 0x00c1
        " ": 
            code: 0x00c2
        "-": 
            code: 0x00c3
        "!": 
            code: 0x00c4
        "[u2]": 
            code: 0x00c5
        "[space3]": 
            code: 0x00c6
        "+": 
            code: 0x00f4
        "?": 
            code: 0x00fc
        ":": 
            code: 0x00fe
        "┌":
            code: 0x0105
        "─":
            code: 0x0106
        "┐":
            code: 0x0107
        "│":
            code: 0x0108
        "┆":
            code: 0x0109
        "└":
            code: 0x010a
        "┄":
            code: 0x010b
        "┘":
            code: 0x010c
        "⇆":
            code: 0x010d
        "█":
            code: 0x010e
        "┏":
            code: 0x0113
        "━":
            code: 0x0114
        "┓":
            code: 0x0115
        "┃":
            code: 0x0116
        "┇":
            code: 0x0117
        "┗":
            code: 0x0118
        "┅":
            code: 0x0119
        "┛":
            code: 0x011a
    Commands:
        "NewLine": 
            code: 0xfffd
            newline: 1
        "HalfNewLine": 
            code: 0xfffe
            newline: 1
        "End": 
            code: 0xffff
